name: lernit_ai
description: A Flutter project for learning AI concepts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.0.2
  googleapis: ^13.1.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+4
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  image_picker: ^1.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  envied: ^0.5.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Remove or comment out the assets/images/ and assets/icons/ entries if the directories do not exist.
  # If you want to keep them, make sure the directories exist and contain at least one file.
  # For now, comment them out to fix the error.
  # assets:
  #   - assets/images/
  #   - assets/icons/